[package]
name = "glv"
version = "3.0.0-beta.5"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"
description = "Git log viewer supporting un/folding merges"
license = "AGPL-3.0-or-later"
repository = "https://github.com/kalkin/git-log-viewer"


[dependencies]
configparser = "3"
crossterm = "^0.22.0"
curl = "0.4.*"
getset = "0.1.*"
git-wrapper = "0.5.*"
git-stree = "0.2.*"
lazy_static = "1.4"
vte = "0.10.1"
posix-errors = "^1.2.0"
regex = "1"
subject-classifier = "0.2.*"
tinyjson = "2"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.7"
unicode-truncate = "0.2.0"
url = "2"
which = "4"
xdg = "^2.1"
clap = { version="^3.0.0", default-features=false, features=["std", "cargo"] }

[dev-dependencies]
lipsum = "^0.8.0"
