[package]
name = "glv"
version = "3.0.0-beta.2"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"
description = "Git log viewer supporting un/folding merges"


[dependencies]
configparser = "2"
crossterm = "0.19"
curl = "0.4.36"
git-wrapper = { path = "../git-wrapper" }
gsi = { path = "../gsi" }
lazy_static = "1.4"
vte = "0.10.1"
posix-errors = { path = "../posix-errors" }
regex = "1"
subject-classifier = { path = "../subject-classifier"}
tinyjson = "2"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.7"
unicode-truncate = "0.2.0"
url = "2"
which = "4"
xdg = "^2.1"

[dev-dependencies]
lipsum = "0.7.0"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["suggestions", "cargo", "color", "std", "wrap_help"]
