[package]
name = "glv"
version = "0.1.0"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16"
git-wrapper = { path = "../git-wrapper" }
vte = "0.10.0"
