[package]
name = "glv"
version = "0.1.0"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "2"
cursive = "0.16"
docopt = "1"
git-wrapper = { path = "../git-wrapper" }
glv-core = { path = "../glv-core" }
log = "0.4"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
vte = "0.10.0"
posix-errors = { path = "../posix-errors" }
unicode-width = "0.1.7"
which = "4"
