### generated by coco
install:
	pip install --user --upgrade .

.PHONY: coverage-html
coverage-html: cover/index.html

.PHONY: coverage
coverage: coverage-bdd

.PHONY: coverage-bdd
coverage-bdd:
	$(ALOE) --with-coverage --cover-package=glv

ifeq ($(V),1)
ALOE ::= aloe -vv
else
ALOE ::= aloe
endif

cover/index.html: features/__init__.py
cover/index.html: $(wildcard glv/**/*.py) $(wildcard features/*.feature)
	$(ALOE) --cover-html --with-coverage --cover-package=glv
.PHONY: check
check:
	tox
ifneq (,$(wildcard docs))
.PHONY: docs
docs:
	$(MAKE) -C docs
endif
