---
name: glv
version: 2.0.0
short-description: git log viewer with foling & unfolding merges support
url: https://github.com/kalkin/git-log-viewer
license: AGPLv3+
long-description:
    content-type: text/markdown
    body: >
        An alternative to `tig(1)`/`lazygit(1) which supports folding merges and
        is expandable via plugins. The application can resolve the default merge
        titles done by using GitHub or Bitbucket to the actual pull request
        names.

keywords: git GitPython tig tui lazygit

install-requirements:
    - Babel >= 2.5.1, <3.0
    - GitPython >= 3.1.11
    - certifi
    - docopt
    - prompt_toolkit >= 2.0, <4.0
    - pygments >= 2.6.0
    - pykka
    - urllib3
    - xdg

test-requirements:
    - aloe
type: python-cli
test-command: tox
data-files:
    man/man1:
        - docs/glv.1
python-classifiers:
    - "Topic :: Software Development :: Version Control :: Git"
entry_points:
    console_scripts:
        - glv=glv.main:cli
    glv_providers:
        - atlassian=glv.providers:Atlassian
        - github=glv.providers:GitHub
    glv_icons:
        - ascii=glv.icons:ASCII
        - nerdfont=glv.icons:NERDFONT
