'\" t
.\"     Title: glv
.\"    Author: Bahtiar `kalkin` Gadimov
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-05-01
.\"    Manual: Git Log Viewer Manual
.\"    Source: Git Log Viewer v1.4.0
.\"  Language: English
.\"
.TH "GLV" "1" "2020-05-01" "Git Log Viewer v1.4.0" "Git Log Viewer Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
glv \- Git Log Viewer a TUI application with support for folding merges
.SH "SYNOPSIS"
.sp
.nf
\fBglv\fP [\-w DIR | \-\-workdir=DIR] [REVISION] [\-d | \-\-debug] \(rs[[\-\-] <path>...]
\fBglv\fP \-\-version
.fi
.br
.SH "DESCRIPTION"
.sp
An alternative to \fBtig\fP(1)/\fBlazygit\fP(1) which supports folding the merges and is
expandable via plugins. The application can resolve the default merge titles
done by using GitHub or Bitbucket to the actual pull request names.
.sp
Use kbd:[CTRL+C] or kbd:[q] to exit the application.
.SH "OPTIONS"
.sp
REVISION
.RS 4
A branch, tag or commit [default: HEAD]
.RE
.sp
\-w DIR, \-\-workdir=DIR
.RS 4
Directory where the git repository is
.RE
.sp
\-d, \-\-debug
.RS 4
Enable sending debugging output to \fBjournalctl\fP(1) (\f(CRjournalctl \-\-user \-f\fP)
.RE
.SH "CONFIGURATION"
.sp
The Git Log Viewer user configuration file is loaded in the following way. If
\f(CR$XDG_CONFIG_HOME\fP is set, read user configuration from
\f(CR$XDG_CONFIG_HOME/glv/config\fP. If \f(CR$XDG_CONFIG_HOME\fP is empty or undefined, read
user configuration from \f(CR~/.config/glv/config\fP.
.sp
The configuration file consists of sections and variables. A section begins with
the name of the section in square brackets and continues until the next section
begins. Section names are case\-insensitive. Only alphanumeric characters, \- and
\&. are allowed in section names. Each variable must belong to some section, which
means that there must be a section header before the first setting of a
variable.
.SS "Variables"
.sp
\fBhistory.icon_set\fP (string)
.RS 4
The set of icons to use for the icon column. Currently only the following
are supported:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
ascii
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
nerdfont ← Install NerdFont to use this
.RE
.RE
.sp
\fBhistory.author_date_color\fP (string), \fBhistory.modules_color\fP (string), \fBhistory.author_name_color\fP (string), \fBhistory.short_id_color\fP (string), \fBhistory.icon_color\fP (string), \fBhistory.subject_color\fP (string), \fBhistory.type_color\fP (string), \fBhistory.branches_color\fP (string)
.RS 4
prompt_toolkit style string \c
.URL "https://python\-prompt\-toolkit.readthedocs.io/en/master/pages/advanced_topics/styling.html" "" ""
.RE
.sp
\fBhistory.author_date_format\fP (string)
.RS 4
One of “full”, “long”, “medium”, or “short”.
.RE
.sp
\fBhistory.author_name_width\fP (string)
.RS 4
The width of the author name column. Default is set to “10”.
.RE
.SH "DEFAULT KEYS"
.SS "General Keys"
.sp
The keys listed in the next two tables are available in all views.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Movement
.TS
allbox tab(:);
lt lt.
T{
.sp
Key
T}:T{
.sp
Action
T}
T{
.sp
kbd:[h]
T}:T{
.sp
Show this help.
T}
T{
.sp
kbd:[k], kbd:[Up]
T}:T{
.sp
Move cursor one line up.
T}
T{
.sp
kbd:[j], kbd:[Down]
T}:T{
.sp
Move cursor one line down.
T}
T{
.sp
kbd:[PgUp],
T}:T{
.sp
Move cursor one page up.
T}
T{
.sp
kbd:[PgDown], kbd:[Space]
T}:T{
.sp
Move cursor one page down.
T}
T{
.sp
kbd:[End]
T}:T{
.sp
Jump to last line.
T}
T{
.sp
kbd:[Tab]
T}:T{
.sp
Move focus to the next view
T}
T{
.sp
kbd:[q]
T}:T{
.sp
Close view, if multiple views are open it will
jump back to the previous view in the view stack.
If it is the last open view it will quit.
T}
T{
.sp
kbd:[Home]
T}:T{
.sp
Jump to first line.
T}
.TE
.sp
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 2. Searching
.TS
allbox tab(:);
lt lt.
T{
.sp
Key
T}:T{
.sp
Action
T}
T{
.sp
kbd:[/]
T}:T{
.sp
Search the view. Opens a prompt for entering search regexp to use.
T}
T{
.sp
kbd:[?]
T}:T{
.sp
Search backwards in the view. Also prompts for regexp.
T}
T{
.sp
kbd:[n]
T}:T{
.sp
Find next match for the current search regexp.
T}
T{
.sp
kbd:[N]
T}:T{
.sp
Find previous match for the current search regexp.
T}
.TE
.sp
.SS "Log View"
.TS
allbox tab(:);
lt lt.
T{
.sp
Key
T}:T{
.sp
Action
T}
T{
.sp
kbd:[Enter]
T}:T{
.sp
Open selected commit in diff view
T}
T{
.sp
kbd:[l]
T}:T{
.sp
Unfold merge or follow the merge if unfolded
T}
T{
.sp
kbd:[h]
T}:T{
.sp
Fold merge or go up the tree if folded
T}
T{
.sp
kbd:[Space]
T}:T{
.sp
Toggle fold/unfold on selected commit
T}
T{
.sp
kbd:[zo]
T}:T{
.sp
Unfold merge or follow the merge if unfolded
T}
T{
.sp
kbd:[zc]
T}:T{
.sp
Fold merge or go up the tree if folded
T}
T{
.sp
kbd:[za]
T}:T{
.sp
Toggle fold/unfold on selected commit
T}
.TE
.sp
.SS "Diff View"
.TS
allbox tab(:);
lt lt.
T{
.sp
Key
T}:T{
.sp
Action
T}
T{
.sp
kbd:[Enter]
T}:T{
.sp
Open selected commit in diff view
T}
T{
.sp
kbd:[{]
T}:T{
.sp
Jump to previous hunk
T}
T{
.sp
kbd:[}]
T}:T{
.sp
Jump to next hunk
T}
.TE
.sp
.SH "AUTHOR"
.sp
Bahtiar `kalkin` Gadimov